{"id":167,"title":"Redis - Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.","imageUrl":"60ac9d5b-1502-4b59-ab20-8f722552f95d_redis-cache.jpg","dateCreated":"2018-12-08T10:33:08.443Z","dateModified":"2018-12-08T11:06:23.541Z","contributedBy":"AskGif","content":"<p>When I am trying to run Django with the latest version of the Redis module, it crashes:</p>\r\n<p>Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.</p>\r\n<p>It's this message. Full stack trace:</p>\r\n<pre class=\"language-markup\"><code>Environment:\r\n\r\n\r\nRequest Method: GET\r\nRequest URL: http://localhost:8000/\r\n\r\nDjango Version: 2.1.3\r\nPython Version: 3.6.3\r\nInstalled Applications:\r\n('django.contrib.auth',\r\n 'django.contrib.contenttypes',\r\n 'django.contrib.sessions',\r\n 'django.contrib.messages',\r\n 'django.contrib.staticfiles',\r\n 'django.contrib.humanize',\r\n 'django.contrib.postgres',\r\n 'django.contrib.sites',\r\n 'django.contrib.flatpages',\r\n 'django.contrib.sitemaps',\r\n 'django.contrib.admin',\r\n 'django.contrib.admindocs',\r\n 'rest_framework',\r\n 'rest_framework_docs',\r\n 'rest_framework.authtoken',\r\n 'drf_yasg',\r\n 'django_bleach',\r\n 'cspreports',\r\n 'captcha',\r\n 'django_markdown2',\r\n 'crispy_forms',\r\n 'api2',\r\n 'headers',\r\n 'worker',\r\n 'cookies',\r\n 'sslyze.apps.CoreConfig',\r\n 'flash',\r\n 'rss',\r\n 'seo',\r\n 'news',\r\n 'contact',\r\n 'browser_extension',\r\n 'adstxt',\r\n 'vuln',\r\n 'busint',\r\n 'csp_analytics',\r\n 'reporting_api',\r\n 'register_site.apps.CoreConfig',\r\n 'utils',\r\n 'stats',\r\n 'phantomjs',\r\n 'malware',\r\n 'paypal.standard.ipn',\r\n 'payments.apps.PaymentsConfig')\r\nInstalled Middleware:\r\n['django.middleware.cache.UpdateCacheMiddleware',\r\n 'django.middleware.gzip.GZipMiddleware',\r\n 'django.middleware.http.ConditionalGetMiddleware',\r\n 'django.contrib.sessions.middleware.SessionMiddleware',\r\n 'django.middleware.locale.LocaleMiddleware',\r\n 'django.middleware.common.CommonMiddleware',\r\n 'django.middleware.clickjacking.XFrameOptionsMiddleware',\r\n 'django.middleware.security.SecurityMiddleware',\r\n 'middleware.dnt.DoNotTrackMiddleware',\r\n 'middleware.preload.ResourceHintsMiddleware',\r\n 'django.middleware.csrf.CsrfViewMiddleware',\r\n 'django.contrib.auth.middleware.AuthenticationMiddleware',\r\n 'django.contrib.messages.middleware.MessageMiddleware',\r\n 'django.middleware.cache.FetchFromCacheMiddleware']\r\n\r\n\r\n\r\nTraceback:\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/django/core/handlers/exception.py\" in inner\r\n  34.             response = get_response(request)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/django/utils/deprecation.py\" in __call__\r\n  90.             response = self.process_request(request)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/django/middleware/cache.py\" in process_request\r\n  137.         cache_key = get_cache_key(request, self.key_prefix, 'GET', cache=self.cache)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/django/utils/cache.py\" in get_cache_key\r\n  335.     headerlist = cache.get(cache_key)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/django_redis/cache.py\" in _decorator\r\n  32.             return method(self, *args, **kwargs)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/django_redis/cache.py\" in get\r\n  81.                                    client=client)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/django_redis/client/default.py\" in get\r\n  202.             value = client.get(key)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/redis/client.py\" in get\r\n  1207.         return self.execute_command('GET', name)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/redis/client.py\" in execute_command\r\n  754.             connection.send_command(*args)\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/redis/connection.py\" in send_command\r\n  619.         self.send_packed_command(self.pack_command(*args))\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/redis/connection.py\" in pack_command\r\n  659.         for arg in imap(self.encoder.encode, args):\r\n\r\nFile \"/home/sumit/wps2/lib/python3.6/site-packages/redis/connection.py\" in encode\r\n  124.                             \"byte, string or number first.\" % typename)\r\n\r\nException Type: DataError at /\r\nException Value: Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.\r\n</code></pre>\r\n<p>&nbsp;</p>\r\n<p>Solution:</p>\r\n<pre class=\"language-markup\"><code>This issue needs to be fixed in django-redis. I think this is not-a-bug as far as redis-py is concerned.\r\n\r\nredis-py 3.0 only accepts keys and values as bytes, strings or numbers. This is a backwards incompatible change listed in the release notes.\r\n\r\nI suspect django-redis needs to be updated to convert the CacheKey type into a string before sending it into redis-py.\r\n\r\n\r\ndjango-redis isn't constraining it's dependency on py-redis to version 2.\r\n\r\n    install_requires=[\r\n        \"Django&gt;=1.11\",\r\n        \"redis&gt;=2.10.0\",\r\n    ],\r\n\r\nI imagine a lot of people are going to get stung by this so expect django-redis to get fixed soon.\r\nIf you can't wait for the fix, you could pin the last v2 of py-redis in your requirements.txt file\r\nredis==2.10.6</code></pre>","ampImage":"https://raw.githubusercontent.com/sumitc91/AmpImage/main/Blogs/60ac9d5b-1502-4b59-ab20-8f722552f95d_redis-cache.jpg","subContents":[],"category":{"name":"coding","slug":"coding"},"slug":"redis-invalid-input-of-type-cachekey.-convert-to-a-byte-string-or-number-first","tags":[{"name":"django","slug":"django"},{"name":"redis","slug":"redis"},{"name":"python","slug":"python"}],"recommendations":[{"id":167,"title":"Redis - Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.","imageUrl":"60ac9d5b-1502-4b59-ab20-8f722552f95d_redis-cache.jpg","dateCreated":"2018-12-08T10:33:08.443Z","dateModified":"2018-12-08T11:06:23.541Z","contributedBy":"AskGif","content":"When I am trying to run Django with the latest version of the Redis module, it crashes:\r\nInvalid input of type: 'CacheKey'. Convert to a byte, string or number first.\r\nIt's this message. Full stack trace:\r\n<pre class=\"language-markup\"><code>Environment:\r\n\r\n\r\nRequest Method: GET\r","ampImage":"https://raw.githubusercontent.com/sumitc91/AmpImage/main/Blogs/60ac9d5b-1502-4b59-ab20-8f722552f95d_redis-cache.jpg","category":{"name":"coding","slug":"coding"},"tags":[{"name":"django","slug":"django"},{"name":"redis","slug":"redis"},{"name":"python","slug":"python"}],"slug":"redis-invalid-input-of-type-cachekey.-convert-to-a-byte-string-or-number-first","total":0}]}